#%RAML 1.0 Library

uses:
  file-types: ../libraries/wmt_mfs_crm_common.raml
  
traits:
  CommonHeader:
    headers:
      Accept-Encoding: file-types.Accept-Encoding
      appId: file-types.ApplicationID
      appVersion: file-types.ApplicationVersion
      versionCode: file-types.VersionCode
      deviceId: file-types.DeviceId
      userLanguage: 
        type: file-types.UserLanguage
        required: false
  LoginHeader:
    headers:
      Accept-Encoding: file-types.Accept-Encoding
      userLanguage: 
        type: file-types.UserLanguage
        required: false