get:
  description: Find POS Address
  queryParameters:
        msisdn:
          type: number
          required: true
          description: The MSISDN of the customer
  responses: 
    200:
      description: On Successful response.  
      body: 
        application/json:
          example: !include         examples/wmt-mfs-crm-pos-address.json
    304:
      description: On unchanged response.