post:
  description: Change Account State
  body: 
    application/x-www-form-urlencoded:      
      properties:
        msisdn:
          type: number
          required: true
          description: The MSISDN of the customer
        active:
          required: true
          type: integer
          description: account status 0 or 1
        suspended:
          required: true
          type: string
          description: account status 0 or 1
        stopped:
          required: true
          type: string
          description: account status 0 or 1
        frozen:
          required: true
          type: string
          description: account status 0 or 1
        reason:
          required: true
          type: string
          description: reason for account state change
  responses: 
    200:
      description: On Successful response.  
      body: 
        application/json:
          example: !include         examples/wmt-mfs-crm-unspecified.json
    304:
      description: On unchanged response.