post:
  description: Reset Status Code
  body: 
    application/x-www-form-urlencoded:      
      properties:
        msisdn:
          required: true
          type: string
          description: MSISDN for secret code reset       
        reason:
          required: true
          type: string
          description: reason for secret code reset      
        transactionId:
          required: true
          type: string
          description: transactionId for secret code reset
  responses: 
    200:
      description: On Successful response.  
      body: 
        application/json:
          example: !include  examples/wmt-mfs-crm-unspecified.json
    304:
      description: On unchanged response.